-- ========================================================
-- TRUSTLANCE AI — DATABASE SEED DATA (MySQL 8.0+)
-- Seed data for demo and evaluation
-- ========================================================

USE `trustlance_ai`;

-- 1. SEED 20 STANDARD SERVICES
INSERT INTO `services` (`id`, `name`, `slug`, `description`, `icon`, `category`, `avg_budget`, `delivery_days`, `project_count`, `is_active`) VALUES
(1, 'Web Development', 'web-development', 'Full-stack web applications, modern responsive React/Next.js platforms, PHP APIs, and custom enterprise SaaS portals.', 'Globe', 'Engineering', 1200.00, 14, 48, 1),
(2, 'Mobile App Development', 'mobile-app-development', 'Native iOS, Android and cross-platform React Native / Flutter apps with verified security standards.', 'Smartphone', 'Engineering', 2400.00, 21, 32, 1),
(3, 'UI/UX Design', 'ui-ux-design', 'Figma user journey mapping, design systems, wireframing, high-fidelity prototypes and conversion design.', 'Palette', 'Design', 950.00, 10, 41, 1),
(4, 'AI & Machine Learning', 'ai-machine-learning', 'LLM integrations, RAG pipelines, model fine-tuning, computer vision, and autonomous agent systems.', 'Cpu', 'AI & Data', 2800.00, 18, 29, 1),
(5, 'Graphic Design', 'graphic-design', 'Brand identity packages, vector illustration, vector logo suites, pitch deck graphics, and marketing assets.', 'Brush', 'Design', 600.00, 7, 36, 1),
(6, 'Video Editing', 'video-editing', 'Professional 4K post-production, sound design, color grading, social media reels, and brand commercials.', 'Film', 'Media', 750.00, 6, 25, 1),
(7, 'Content Writing', 'content-writing', 'Technical documentation, executive whitepapers, high-converting copy, and authoritative editorial articles.', 'FileText', 'Writing', 450.00, 5, 39, 1),
(8, 'Digital Marketing', 'digital-marketing', 'Growth marketing funnels, performance advertising (Meta, Google, LinkedIn), and multi-channel attribution.', 'TrendingUp', 'Marketing', 1100.00, 14, 28, 1),
(9, 'Data Analysis', 'data-analysis', 'BI dashboard development, SQL analytics, predictive modeling, Python data cleaning, and KPI reporting.', 'BarChart3', 'AI & Data', 1300.00, 10, 22, 1),
(10, 'Cybersecurity', 'cybersecurity', 'Web penetration testing, OWASP compliance auditing, SOC2 readiness, and zero-trust cloud configuration.', 'ShieldCheck', 'Engineering', 3200.00, 14, 18, 1),
(11, 'Cloud Computing', 'cloud-computing', 'AWS, Google Cloud & Azure infrastructure deployment, serverless scaling, and cloud cost optimization.', 'Cloud', 'Engineering', 1800.00, 12, 24, 1),
(12, 'DevOps', 'devops', 'CI/CD pipeline automation, Docker containerization, Kubernetes orchestration, and monitoring telemetry.', 'GitBranch', 'Engineering', 1950.00, 10, 26, 1),
(13, 'Game Development', 'game-development', 'Unity and Unreal Engine gameplay programming, 2D/3D mechanics, multiplayer networking, and shader logic.', 'Gamepad2', 'Creative Tech', 3500.00, 30, 14, 1),
(14, 'Blockchain Development', 'blockchain-development', 'Solidity smart contracts, EVM audits, dApp Web3 integrations, and automated token economics.', 'Coins', 'Engineering', 3800.00, 20, 16, 1),
(15, 'SEO', 'seo', 'Technical site auditing, high-intent keyword mapping, core web vitals speed optimization, and link authority.', 'Search', 'Marketing', 850.00, 14, 31, 1),
(16, 'Animation & 3D', 'animation-3d', 'Blender 3D modeling, photorealistic product rendering, motion graphics, and character animation.', 'Sparkles', 'Media', 1400.00, 12, 19, 1),
(17, 'Photography', 'photography', 'Commercial studio product photography, architectural shoots, high-end editorial retouching.', 'Camera', 'Media', 650.00, 5, 17, 1),
(18, 'Voice Over', 'voice-over', 'Studio-quality commercial voice acting, audiobook narration, multilingual dubbing, and podcast intros.', 'Mic', 'Media', 350.00, 3, 21, 1),
(19, 'Translation', 'translation', 'Professional localization across 35+ languages, legal & technical contract translation, and proofreading.', 'Languages', 'Writing', 400.00, 4, 27, 1),
(20, 'IoT Development', 'iot-development', 'Embedded firmware (C/C++), ESP32/Raspberry Pi hardware prototypes, MQTT telemetry, and edge logic.', 'Wifi', 'Engineering', 2600.00, 25, 12, 1)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);

-- 2. SEED SKILLS
INSERT INTO `skills` (`id`, `name`, `category`) VALUES
(1, 'React', 'Frontend'),
(2, 'TypeScript', 'Frontend'),
(3, 'PHP', 'Backend'),
(4, 'MySQL', 'Database'),
(5, 'Node.js', 'Backend'),
(6, 'Python', 'AI/Data'),
(7, 'Figma', 'Design'),
(8, 'Tailwind CSS', 'Frontend'),
(9, 'Docker', 'DevOps'),
(10, 'AWS', 'Cloud'),
(11, 'Smart Contracts', 'Web3'),
(12, 'SEO Strategy', 'Marketing')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);

-- 3. SEED USERS (Password hashes for demonstration; all passwords comply with password_hash())
-- Password for all demo accounts: 'TrustLance2026!' or specific role passwords
-- Hash generated by password_hash('TrustLance2026!', PASSWORD_BCRYPT)
-- '$2y$10$wT0o3qBf5F8.hVUkI3lUteXq4bAkgUqRsmZkPZ4y7cZ3fC1f3z7pW'
INSERT INTO `users` (`id`, `email`, `password_hash`, `full_name`, `role`, `avatar_url`, `phone`, `status`) VALUES
(1, 'customer@demo.com', '$2y$10$wT0o3qBf5F8.hVUkI3lUteXq4bAkgUqRsmZkPZ4y7cZ3fC1f3z7pW', 'Sarah Jenkins', 'customer', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', '+1 (555) 234-5678', 'active'),
(2, 'freelancer@demo.com', '$2y$10$wT0o3qBf5F8.hVUkI3lUteXq4bAkgUqRsmZkPZ4y7cZ3fC1f3z7pW', 'Elena Vance', 'freelancer', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150', '+1 (555) 345-6789', 'active'),
(3, 'admin@demo.com', '$2y$10$wT0o3qBf5F8.hVUkI3lUteXq4bAkgUqRsmZkPZ4y7cZ3fC1f3z7pW', 'Alex Sterling', 'admin', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', '+1 (555) 999-0000', 'active'),
(4, 'marcus@brody.dev', '$2y$10$wT0o3qBf5F8.hVUkI3lUteXq4bAkgUqRsmZkPZ4y7cZ3fC1f3z7pW', 'Marcus Brody', 'freelancer', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150', '+1 (555) 456-7890', 'active'),
(5, 'sophia@uxstudio.com', '$2y$10$wT0o3qBf5F8.hVUkI3lUteXq4bAkgUqRsmZkPZ4y7cZ3fC1f3z7pW', 'Sophia Reed', 'freelancer', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150', '+1 (555) 567-8901', 'active'),
(6, 'liam@codecraft.io', '$2y$10$wT0o3qBf5F8.hVUkI3lUteXq4bAkgUqRsmZkPZ4y7cZ3fC1f3z7pW', 'Liam Gallagher', 'freelancer', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150', '+1 (555) 678-9012', 'active'),
(7, 'david@kimsecure.net', '$2y$10$wT0o3qBf5F8.hVUkI3lUteXq4bAkgUqRsmZkPZ4y7cZ3fC1f3z7pW', 'David Kim', 'freelancer', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150', '+1 (555) 789-0123', 'active')
ON DUPLICATE KEY UPDATE `email`=VALUES(`email`);

-- 4. CUSTOMER PROFILE
INSERT INTO `customers` (`id`, `user_id`, `company_name`, `industry`, `trust_score`, `verified_payment`, `total_spent`, `completed_projects`, `dispute_count`) VALUES
(1, 1, 'Aetheria Cloud Technologies', 'FinTech & AI SaaS', 96.50, 1, 14250.00, 8, 0)
ON DUPLICATE KEY UPDATE `company_name`=VALUES(`company_name`);

-- 5. FREELANCER PROFILES & SCORES
INSERT INTO `freelancers` (`id`, `user_id`, `headline`, `bio`, `hourly_rate`, `project_rate`, `trust_score`, `rating`, `review_count`, `completed_projects`, `on_time_delivery_rate`, `response_time_hours`, `availability`) VALUES
(1, 2, 'Senior AI Engineer & Full-Stack Architect', 'Over 8 years developing production enterprise platforms. Specializing in LLM pipelines, React/Vite, PHP 8.2 PDO backends, and high-security fintech escrow workflows.', 85.00, 1800.00, 99.20, 4.98, 47, 52, 100.00, 0.8, 'available'),
(2, 4, 'Cloud & DevOps Solutions Architect', 'AWS Certified Solutions Architect & Kubernetes specialist. Automating zero-downtime CI/CD workflows, Docker orchestration, and high-availability MySQL clusters.', 95.00, 2200.00, 94.40, 4.92, 34, 38, 97.50, 1.2, 'available'),
(3, 5, 'Principal Product Designer & Design Systems Lead', 'Crafting user-centric FinTech and AI SaaS interfaces with Figma. Expert in design tokens, accessible UX components, and high-conversion enterprise landing pages.', 75.00, 1400.00, 88.60, 4.89, 29, 31, 95.00, 2.0, 'available'),
(4, 6, 'Full-Stack Web & API Developer', 'Building robust database-driven web solutions using React, PHP, and MySQL. Passionate about clean code, test coverage, and responsive layout fidelity.', 55.00, 900.00, 76.50, 4.65, 14, 16, 91.00, 3.5, 'available'),
(5, 7, 'Cybersecurity & Pentesting Specialist', 'Certified Ethical Hacker (CEH) performing web application security audits, vulnerability scanning, code reviews, and OWASP compliance verification.', 90.00, 2000.00, 62.00, 4.40, 6, 7, 85.00, 5.0, 'busy')
ON DUPLICATE KEY UPDATE `headline`=VALUES(`headline`);

-- 6. ADMIN PROFILE
INSERT INTO `admins` (`id`, `user_id`, `department`, `access_level`) VALUES
(1, 3, 'Trust & Safety Operations', 'super_admin')
ON DUPLICATE KEY UPDATE `department`=VALUES(`department`);

-- 7. FREELANCER SKILLS
INSERT INTO `freelancer_skills` (`freelancer_id`, `skill_id`, `proficiency`) VALUES
(1, 1, 'expert'), (1, 2, 'expert'), (1, 3, 'expert'), (1, 4, 'expert'), (1, 6, 'expert'),
(2, 9, 'expert'), (2, 10, 'expert'), (2, 4, 'advanced'),
(3, 7, 'expert'), (3, 8, 'advanced'), (3, 1, 'intermediate'),
(4, 1, 'advanced'), (4, 3, 'advanced'), (4, 4, 'advanced')
ON DUPLICATE KEY UPDATE `proficiency`=VALUES(`proficiency`);

-- 8. AI TRUST SCORES DETAIL
INSERT INTO `ai_scores` (`id`, `freelancer_id`, `total_score`, `tier_level`, `completion_factor`, `on_time_factor`, `rating_factor`, `response_factor`, `repeat_client_factor`, `dispute_penalty`) VALUES
(1, 1, 99.20, 'Elite', 100.00, 100.00, 99.60, 98.50, 95.00, 0.00),
(2, 2, 94.40, 'Highly Trusted', 97.50, 97.50, 98.40, 92.00, 88.00, 0.00),
(3, 3, 88.60, 'Trusted', 95.00, 95.00, 97.80, 85.00, 75.00, 0.00),
(4, 4, 76.50, 'Good', 91.00, 91.00, 93.00, 72.00, 60.00, 0.00),
(5, 5, 62.00, 'Average', 85.00, 85.00, 88.00, 60.00, 45.00, 5.00)
ON DUPLICATE KEY UPDATE `total_score`=VALUES(`total_score`);

-- 9. PROJECTS
INSERT INTO `projects` (`id`, `customer_id`, `service_id`, `title`, `description`, `requirements`, `budget`, `deadline`, `status`, `revision_expectations`, `selected_freelancer_id`) VALUES
(1, 1, 1, 'Enterprise AI Analytics Portal with Secure Escrow', 'Looking for an experienced engineer to build an end-to-end analytics dashboard with real-time data feeds, user role permissions, and transactional reporting.', '1. Modern React frontend with Tailwind/Bootstrap.\n2. Clean PHP 8.2 backend with PDO.\n3. MySQL database with indexes.\n4. Simulated Escrow workflow.', 2400.00, '2026-10-15', 'in_progress', '2 comprehensive rounds included.', 1),
(2, 1, 3, 'FinTech SaaS Mobile App Design System', 'Comprehensive UI/UX design in Figma including mobile application screens, dark/light theme component library, and interactive prototypes.', 'Deliverables must include Figma source files, tokens, and exportable SVG assets.', 1100.00, '2026-10-05', 'open', '3 design critique revisions.', NULL),
(3, 1, 4, 'Autonomous LLM Agent for Customer Support Triage', 'Develop an AI microservice that parses incoming user inquiries, classifies intent, and synthesizes accurate answers grounded in our documentation database.', 'Requires Python or Node microservice with structured JSON responses and error fallbacks.', 3200.00, '2026-11-01', 'open', '2 technical validation rounds.', NULL),
(4, 1, 10, 'SOC2 Cloud Security Audit & Pen-Test', 'Perform an external and internal penetration test on our cloud API endpoints and report vulnerabilities mapped to OWASP Top 10.', 'Full executive summary and remediations report required.', 1800.00, '2026-09-30', 'completed', 'Standard verification check.', 5)
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- 10. PROPOSALS
INSERT INTO `proposals` (`id`, `project_id`, `freelancer_id`, `cover_letter`, `proposed_price`, `delivery_days`, `relevant_experience`, `status`, `ai_match_score`, `ai_match_reason`) VALUES
(1, 1, 1, 'Hello Sarah, I have built multiple enterprise SaaS portals with PHP 8.2 PDO and React. My Trust Score is 99.2 (Elite Tier), and I have completed 52 on-time projects with zero escrow disputes. I can deliver this system with clean architecture, prepared statements, and verified milestones.', 2400.00, 14, 'Built scalable FinTech dashboards with simulated escrow for Fortune 500 clients.', 'accepted', 97.80, 'Top skill alignment in React, PHP, MySQL with 100% on-time record and Elite trust tier.'),
(2, 1, 4, 'Hi Sarah, I would love to tackle the analytics portal. I specialize in full-stack React and PHP architecture. I can structure the MySQL schema cleanly.', 2100.00, 16, 'Developed 14 web applications using modern full-stack tools.', 'rejected', 82.40, 'Solid skill match in React and PHP; slightly lower historic volume of completed enterprise projects.'),
(3, 2, 3, 'Hi Sarah! As a Principal Product Designer specializing in FinTech, I have designed 20+ design systems with dark/light mode fidelity. I will provide a modular Figma design token library.', 1100.00, 9, 'Led design systems for two Series-A fintech startups.', 'pending', 94.50, 'High domain match in FinTech UX, verified portfolio tokens, and 95% on-time delivery rate.')
ON DUPLICATE KEY UPDATE `status`=VALUES(`status`);

-- 11. MILESTONES FOR PROJECT 1
INSERT INTO `milestones` (`id`, `project_id`, `title`, `description`, `amount`, `deadline`, `status`, `order_index`) VALUES
(1, 1, 'Architecture & Database Schema Design', 'Complete normalized MySQL 8.0 schema, PDO connection setup, and API routes definition.', 800.00, '2026-09-28', 'approved', 1),
(2, 1, 'Frontend Workspace & Core Dashboards', 'React dashboard layout, interactive metrics charts, and live filter panels.', 800.00, '2026-10-06', 'in_progress', 2),
(3, 1, 'Escrow State Machine & Final Audit', 'Escrow release workflow, security checks, and final deployment documentation.', 800.00, '2026-10-15', 'funded_escrow', 3)
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- 12. ESCROW ACCOUNT FOR PROJECT 1 (Payment Secured)
INSERT INTO `escrow_accounts` (`id`, `project_id`, `customer_id`, `freelancer_id`, `total_amount`, `held_amount`, `released_amount`, `refunded_amount`, `status`) VALUES
(1, 1, 1, 1, 2400.00, 1600.00, 800.00, 0.00, 'partially_released')
ON DUPLICATE KEY UPDATE `held_amount`=VALUES(`held_amount`);

-- 13. ESCROW TRANSACTIONS FOR PROJECT 1
INSERT INTO `escrow_transactions` (`id`, `escrow_id`, `type`, `amount`, `status`, `reference_id`, `notes`) VALUES
(1, 1, 'fund', 2400.00, 'success', 'TX-ESCROW-2026-9041', 'Customer funded total project escrow into TrustLance AI Vault'),
(2, 1, 'release', 800.00, 'success', 'TX-REL-2026-9042', 'Milestone 1 approved by customer. AI Broker released $800.00 to Freelancer wallet')
ON DUPLICATE KEY UPDATE `reference_id`=VALUES(`reference_id`);

-- 14. DELIVERABLES
INSERT INTO `deliverables` (`id`, `project_id`, `milestone_id`, `freelancer_id`, `title`, `notes`, `file_path`, `version`, `status`) VALUES
(1, 1, 1, 1, 'Architecture & Database Specification v1.0', 'Includes normalized schema.sql, seed data, and API contract specifications.', '/uploads/deliverables/schema_spec_v1.pdf', 1, 'approved'),
(2, 1, 2, 1, 'Frontend Workspace Dashboard Components v1.1', 'Integrated responsive charts, dark mode support, and state machine controls.', '/uploads/deliverables/workspace_v1.zip', 1, 'submitted')
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- 15. MESSAGES
INSERT INTO `messages` (`id`, `project_id`, `sender_id`, `recipient_id`, `message_text`, `is_read`) VALUES
(1, 1, 1, 2, 'Welcome aboard Elena! The project escrow is fully funded and secured in the TrustLance AI vault.', 1),
(2, 1, 2, 1, 'Thank you Sarah! I have already completed Milestone 1 schema design and uploaded the documentation for your review.', 1),
(3, 1, 1, 2, 'Reviewed and approved Milestone 1. The AI Broker just released the first $800.00 tranche to your wallet!', 1)
ON DUPLICATE KEY UPDATE `message_text`=VALUES(`message_text`);

-- 16. NOTIFICATIONS
INSERT INTO `notifications` (`id`, `user_id`, `title`, `message`, `type`, `link`, `is_read`) VALUES
(1, 1, 'Milestone 2 Deliverable Submitted', 'Elena Vance has submitted Milestone 2: Frontend Workspace Dashboard Components for your review.', 'deliverable', '/customer/projects/1', 0),
(2, 2, 'Escrow Payment Secured', '$2,400.00 has been secured in TrustLance AI Escrow for project: Enterprise AI Analytics Portal.', 'escrow', '/freelancer/projects/1', 1),
(3, 3, 'System Health Nominal', 'All 20 services active. AI Trust Score audit completed with zero anomalies.', 'system', '/admin/dashboard', 1)
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- 17. WALLETS
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `pending_balance`, `total_withdrawn`) VALUES
(1, 1, 5600.00, 1600.00, 0.00),
(2, 2, 800.00, 1600.00, 12400.00),
(3, 4, 340.00, 0.00, 8900.00)
ON DUPLICATE KEY UPDATE `balance`=VALUES(`balance`);

-- 18. REVIEWS
INSERT INTO `reviews` (`id`, `project_id`, `reviewer_id`, `reviewee_id`, `rating`, `comment`) VALUES
(1, 4, 1, 7, 4.8, 'David performed an exemplary penetration test on our endpoints. Detailed vulnerability matrix and actionable remediations provided ahead of schedule.')
ON DUPLICATE KEY UPDATE `rating`=VALUES(`rating`);

-- 19. RISK ALERTS
INSERT INTO `risk_alerts` (`id`, `user_id`, `project_id`, `risk_level`, `reason`, `status`) VALUES
(1, 7, 4, 'Low Risk', 'Routine payment verification check completed successfully.', 'dismissed')
ON DUPLICATE KEY UPDATE `risk_level`=VALUES(`risk_level`);

-- 20. ACTIVITY LOGS
INSERT INTO `activity_logs` (`id`, `user_id`, `action`, `entity`, `entity_id`, `metadata`) VALUES
(1, 1, 'CREATE_PROJECT', 'projects', 1, '{"budget": 2400.00, "service": "Web Development"}'),
(2, 1, 'FUND_ESCROW', 'escrow_accounts', 1, '{"amount": 2400.00, "method": "demo_escrow"}'),
(3, 1, 'APPROVE_MILESTONE', 'milestones', 1, '{"milestone_id": 1, "released_amount": 800.00}')
ON DUPLICATE KEY UPDATE `action`=VALUES(`action`);
